# set -g default-terminal "screen-256color"
source "/usr/share/powerline/bindings/tmux/powerline.conf"

set-option -g default-shell /bin/zsh
set -g default-terminal "xterm-256color"
# set -g status-right "#[fg=silver]#H #(date +'%a,%d %b %Y, %R')"
# set -g mouse on
setw -g mode-keys vi
set -g base-index 1
set -g status-left ""
set -g status-right-length 60
set-option -g allow-rename off
set-option -g renumber-windows on

# Plugins
run '~/.tmux/plugins/tpm/tpm'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
set -g @continuum-restore 'on'
set -g @resurrect-save 'on'
set -g @continuum-save-interval '15'

set -g @resurrect-save 'S'

# set -g status-right '#{battery_level} #{battery_status_bg} Bat: #{battery_graph} #{battery_percentage} < Cpu: #{cpu_percentage} | %a %d-%h-%Y %H:%M'
# set -g status-right '#{online_status} #{battery_level} Cpu: #{cpu_percentage} | %a %d-%h-%Y %H:%M'

set -g @continuum-restore 'on'
set -g @batt_icon_charge_tier7 '🌖'
set -g @batt_icon_charge_tier6 '🌖'
set -g @batt_icon_charge_tier5 '🌗'
set -g @batt_icon_charge_tier4 '🌗'
set -g @batt_icon_charge_tier3 '🌘'
set -g @batt_icon_charge_tier2 '🌘'
set -g @batt_icon_charge_tier1 '🌑'
set -g @batt_icon_status_charged '🔋'
set -g @batt_icon_status_charging '⚡'
set -g @batt_icon_status_discharging '👎'
set -g @batt_color_status_primary_charged '#3daee9'
set -g @batt_color_status_primary_charging '#3daee9'

# Habilita a nevagação no mesmo modelo usado no vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# usa <prefix> Shift-e usado para sincronizar os comandos entre os paines.
bind E setw synchronize-panes

# Usa a letra T para ir diretamente para janela 2 e acessar o tasks
bind T select-window -t 2 \; send-keys "ssh -qt ubuntu@manager-server.agilize.com.br -p 35222 ssh agilize-tasks" Enter
bind S select-window -t 3 \; send-keys "ssh -qt ubuntu@manager-server.agilize.com.br -p 35222 ssh agilize-server" Enter
